[modules]
autoload = yes
; Гарантируем загрузку нужных для WebRTC + ARI модулей
preload = res_pjsip.so
preload = res_pjsip_session.so
preload = res_http_websocket.so
preload = res_ari.so
preload = res_ari_channels.so
preload = res_ari_bridges.so
preload = res_ari_endpoints.so
preload = res_ari_events.so
preload = res_stasis.so
preload = res_stasis_answer.so
preload = res_stasis_playback.so
preload = res_stasis_recording.so
preload = res_srtp.so
